//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationHistory
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string ConnID { get; set; }
        public string UserGroup { get; set; }
        public string Message { get; set; }
    }
}
