//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Topics
    {
        public int id { get; set; }
        [DisplayName("Сообщение*")]
        public string title { get; set; }
        [DisplayName("Добавить изображение*")]
        public string imageone { get; set; }
        [DisplayName("Ссылка на источник")]
        public string imagetwo { get; set; }
        public Nullable<int> countLikes { get; set; }
    }
}
