//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Topics
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Please insert your text")]
        [StringLength(1000, MinimumLength = 20, ErrorMessage = "Our policy means that all new Topics must be at least 6 characters long")]
        public string title { get; set; }
        public string imageone { get; set; }
        public string imagetwo { get; set; }
        public Nullable<int> countLikes { get; set; }
       
    }
}
