//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public System.Guid UserId { get; set; }
        public System.Guid ApplicationId { get; set; }
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        public bool IsAnonymous { get; set; }
        [Display(Name = "Last Activity Date")]
        public System.DateTime LastActivityDate { get; set; }
    }
}
